main: phonon.puppet.PuppetPlugin
name: puppet
version: 0.1.1
softdepend: [kotlin]
commands:
  puppet:
    description: Manage puppet
    aliases: [pp]
    permission: puppet.command.puppet
    usage: /puppet help
  actor:
    description: Actor manipulation commands
    aliases: [a, act]
    permission: puppet.command.actor
    usage: /actor help